framework:
    messenger:
        failure_transport: failed

        transports:
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: messages
                        type: direct
                    queues:
                        messages: ~
                retry_strategy:
                    max_retries: 3
                    multiplier: 2

            evaluate_flush:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: evaluate_flush
                        type: direct
                    queues:
                        evaluate_flush:
                            binding_keys: ['evaluate_flush']
                retry_strategy:
                    max_retries: 0
                    delay: 0

            failed: 'doctrine://default?queue_name=failed'

        default_bus: messenger.bus.default

        buses:
            messenger.bus.default:
                middleware:
                    - doctrine_ping_connection
                    - doctrine_close_connection
                    - doctrine_transaction

        routing:
            'App\Message\EvaluateFlushMessage': evaluate_flush
